from .replicate.qwen_image import (
    NODE_CLASS_MAPPINGS as _QWEN_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _QWEN_NODE_DISPLAY_NAME_MAPPINGS,
    QwenImage,
)

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(_QWEN_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(_QWEN_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = [
    "QwenImage",
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
